name: Maven Build

on:
  push:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Maven Build
        uses: rosestack/maven-build-action@main
        with:
          java-version: 25
